##### Import Libraries

In [6]:
import pandas as pd
import requests
from io import BytesIO

##### Filepath to Census SAIPE 2022 National/State/County Poverty Data

In [7]:
download_filepath = f'https://www2.census.gov/programs-surveys/saipe/datasets/2022/2022-state-and-county/est22all.xls'

##### Load data from filepath

In [8]:
# Download the Excel file from the URL
response = requests.get(download_filepath)
excel_data = response.content

# Read the downloaded Excel file using pandas
df = pd.read_excel(BytesIO(excel_data))

##### Check dataframe

In [9]:
df.head()

,Table with column headers in rows 3 and 4,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30
0,2022 Poverty and Median Household Income Estim...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Geographic Information,NaN,NaN,NaN,All Ages,NaN,NaN,NaN,NaN,NaN,...,NaN,Median Household Income,NaN,NaN,Age 0-4,NaN,NaN,NaN,NaN,NaN
2,State FIPS Code,County FIPS Code,Postal Code,Name,"Poverty Estimate, All Ages",90% CI Lower Bound,90% CI Upper Bound,"Poverty Percent, All Ages",90% CI Lower Bound,90% CI Upper Bound,...,90% CI Upper Bound,Median Household Income,90% CI Lower Bound,90% CI Upper Bound,"Poverty Estimate, Age 0-4",90% CI Lower Bound,90% CI Upper Bound,"Poverty Percent, Age 0-4",90% CI Lower Bound,90% CI Upper Bound
3,00,000,US,United States,40951625,40691315,41211935,12.6,12.5,12.7,...,15.7,74755,74607,74903,3141107,3093587,3188627,17.4,17.1,17.7
4,01,000,AL,Alabama,798469,780933,816005,16.2,15.8,16.6,...,21.6,59703,58986,60420,68982,64247,73717,24.4,22.7,26.1

##### Save to **census_Poverty/data/RAW_2022_SAIPE_DATA.xlsx**

In [10]:
out_filepath = f'../census_Poverty/data/RAW_2022_SAIPE_DATA.xlsx'
df.to_excel(out_filepath, index=False)